fix: Hyprland window alignment
emacs-eaf/emacs-application-framework pull request #1061
Opened 2023-02-18 13:34 UTC by mumu-lhl

Hyprland 上设置窗口大小会导致窗口坐标发生变化，可能因此挡住一部分标签栏。

我尝试使用 move 方法改变窗口位置，但是无效。这个补丁使用 `hyprctl` 实现改变窗口位置。

2023-02-18 14:35 UTC, manateelazycat requested changes

2023-02-18 14:35 UTC, manateelazycat commented on core/view.py
> +            hyprland_window_move(self.x, self.y)
为什么要在 eventFilter 里面加？ 这个函数任何事件发生都会触发的， 比如你动一下鼠标就会导致一秒钟几十次 subprocess 调用， 不会卡吗？

2023-02-18 15:12 UTC, mumu-lhl commented on core/view.py
> +            hyprland_window_move(self.x, self.y)
主要是我不知道该把这段代码加到哪里了 😂 试着往这一加，有效果就写提交了 🤣

感谢解答这个函数的作用，否则我还不知道这个函数是用来干什么的。

我在使用中没有感觉特别卡。

我再试试往其他地方加吧 😂

2023-02-19 11:00 UTC, manateelazycat requested changes

2023-02-19 11:00 UTC, manateelazycat commented on core/view.py
> +            hyprland_window_move(self.x, self.y)
或者你打印一下 event.type() , 看看哪些事件会引起问题？ 只在特定的事件才调用你的 hyprland_window_move, 不要所有事件都调用， 这样会好一点。

2023-02-19 12:31 UTC, manateelazycat requested changes

2023-02-19 12:31 UTC, manateelazycat commented on core/utils.py
> +    if (x - window_x == 0 and y - window_y == 0) is False:
写成 x - window_x != 0 or y - window_y !=0 应该会清晰点。

2023-02-19 12:41 UTC, manateelazycat requested changes

2023-02-19 12:41 UTC, manateelazycat commented on core/view.py
> +        if os.getenv("XDG_CURRENT_DESKTOP") == "Hyprland" and event.type() in [QEvent.Type.Enter]:
这个 XDG_CURRENT_DESKTOP 初始化的时候存储到类属性吧， 不用 eventFilter 每次都取一下， 提高性能。

2023-02-19 13:26 UTC, merged

2023-02-19 13:30 UTC, manateelazycat commented
我稍微改了一下 https://github.com/emacs-eaf/emacs-application-framework/commit/81b586cd109465b93076483b2908a78fc836ae40

避免每次创建一个窗口就要取一次环境变量。